### PR TITLE
Incorporation of big_datafile

### PR DESCRIPTION
**Pull request by nachoaz**
Firstly: `reindent`ed all .py scripts so that they'd all have 4 spaces as indents (a lot of the `diff`s will be only that).

More importantly:
Wrote utils/data_utils.py which allows the user to specify (via two new config items -- "datasource" and "tkrlist") the source from which he or she wishes the data to be fetched from, and the tickers he or she wants the newly-fetched dataset to have.

Also wrote functionality to fetch data using "big_datafile" (basically a big file that we'll construct periodically from which we can "shave off" whatever we want to actually use in experimenting).

Wrote documentation for batch_generator.py and created a directory for utils and another for models.

Began making changes to get caches to load faster.

Pending:
  - functionality to fetch data using WRDS as a source
  - functionality to fetch dataset made up of specified features (both for big_datafile and for WRDS)

### CODE REVIEW

**Comment by euclidjda** [comment]
Here are my suggested changes to this pull request:

1. To keep things simple let's have a top level directory called datasets and just put all data in it (including the ticker list).

2. The standard data file format for deep quant is space separated fields (rather than comma sep) with the .dat suffix. So, let's use that for tkrlist

3. Instead of tkrlist let's use the name ticlist because in other places tic is used to abbreviate ticker.

4. Instead of big_dataset.dat let's call it open_dataset.dat since this is the open source version of a deep-quant dataset.

5. I understand your thinking in adding the fetching/generation of data to the train.py but I would like to keep in separate so that download, preprocessing, training, and predicting are separate steps in the pipeline. That is, train.py should require a datafile in the proper format in data_dir. I think if we try to put everything into a monolithic process it will get too unwieldy. In the long run there may be many different way of getting data from different sources and vendors and these may be in different stages of development at different times. Sound good?

6. To that end, and I know you are not here yet but, if you do add a "Downloading the Data" section to the README, I would like it to describe your (the open) process for download the data. It could then say something like "If you have access to WRDS through a academic  institution, click here to read documentation of downing and using WRDS data."

**Comment by nachoaz** [comment]
1. sure. done.
2. agreed. done.
3. sounds good. done.
4. sure. done.
5. Sounds good. How about I write a "create_datafile" function within data_utils.py and have that either be called by the user as a preliminary step or be called from deep_quant.py, before train() is called? That way, the corresponding .dat file gets generated separately from train.py. Would that work?
6. How about a "Download the Data" section in which first describe how to use deep_quant's scripts to generate the desired .dat file, and _later_ we have links (to findata_fetcher's .README and to the WRDS .README) so that the interested reader may then read a description of how those tools are used to generate the data (I'll make sure to edit those .READMEs as needed to describe what goes on under the hood). How's that? I can keep the complete description of how findata_fetcher gets the data in deep_quant's .README, though, if you think that's important. The reason why I'm suggesting to have it separate is to keep deep_quant's .README focused, and to point the user towards the code used by findata_fetcher in case he or she wants to see/change it.

**Comment by euclidjda** [comment]
1-4. Great. Thanks!

5. Yes on create_datafile() in data_utils.py. Then maybe we create a prepare_datafile.py with flags --data_dir, --source, --dest, and --ticlist. How does that sound?

6. Yes. That all sounds great.

**Comment by nachoaz** [comment]
Sounds great. I'll get started on that right away.

**Comment by nachoaz** [comment]
I finished with prepare_datafile.py and create_datafile().
Now, the user can create system_test_dataset.dat by running:
`python scripts/prepare_datafile.py system_test_ticlist.dat system_test_dataset.dat`

**Comment by euclidjda** [comment]
Looks good. Tested changes on compustat datasets and nothing broke so I will go ahead and merge.

**Pull request merged**
